export const holiday_api = [
  {
    id: "01",
    weakly: "tuesday",
    date: "january 26,2022",
    holiday: "Republic Day",
    color: "gray",
  },
  {
    id: "02",
    weakly: "friday",
    date: "April 2,2022",
    holiday: "Good friday",
    color: "orange",
  },
  {
    id: "03",
    weakly: "Monday",
    date: "April 30,2022",
    holiday: "Independence Day",
    color: "green",
  },
  {
    id: "04",
    weakly: "Tuesday",
    date: "December 25, 2022",
    holiday: "Christmas Day",
    color: "blue",
  },
  {
    id: "05",
    weakly: "tuesday",
    date: "january 26,2022",
    holiday: "Republic Day",
    color: "gray",
  },
  {
    id: "06",
    weakly: "friday",
    date: "April 2,2022",
    holiday: "Good friday",
    color: "orange",
  },
  {
    id: "07",
    weakly: "Monday",
    date: "April 30,2022",
    holiday: "Independence Day",
    color: "blue",
  },
  {
    id: "08",
    weakly: "Tuesday",
    date: "December 25, 2022",
    holiday: "Christmas Day",
    color: "green",
  },
];
